
package estructuradedatos;


import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.*;


 //* @author Yael

public class Menu extends javax.swing.JFrame implements Runnable{
    String hora, minutos, segundos;
    Thread hilo;

    /**
     * Creates new form Principal
     */
    public Menu() {
        initComponents();
        
         this.setLocationRelativeTo(null);
        Fecha.setText(fecha());
        
        hilo= new Thread(this);
        hilo.start();
        setVisible(true);
        
  
        
    }
    
    public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date horaactual=new Date();
        calendario.setTime(horaactual);
        hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos= calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
     public void run(){
         Thread current= Thread.currentThread();
         while(current== hilo){
             hora();
             Hora.setText(hora+":"+minutos+":"+segundos);
}
         
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BtnSalida = new javax.swing.JButton();
        matrizTiBtn = new javax.swing.JButton();
        matrizDispersaBtn = new javax.swing.JButton();
        burbujaBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(102, 0, 102)));
        jPanel3.setMaximumSize(new java.awt.Dimension(1000, 562));
        jPanel3.setMinimumSize(new java.awt.Dimension(1000, 562));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Estructura de datos");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel2);
        jLabel2.setBounds(220, 50, 340, 50);

        Fecha.setBackground(new java.awt.Color(255, 204, 204));
        Fecha.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setText("DD / MM / YYYY");
        Fecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(Fecha);
        Fecha.setBounds(600, 0, 210, 60);

        Hora.setBackground(new java.awt.Color(255, 204, 204));
        Hora.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        Hora.setForeground(new java.awt.Color(255, 255, 255));
        Hora.setText("00:00");
        jPanel3.add(Hora);
        Hora.setBounds(50, 0, 210, 60);

        jPanel4.setBackground(new java.awt.Color(204, 153, 255));
        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));
        jPanel3.add(jPanel4);
        jPanel4.setBounds(10, 10, 760, 40);

        BtnSalida.setBackground(new java.awt.Color(0, 153, 153));
        BtnSalida.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        BtnSalida.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalida.setText("Salir");
        BtnSalida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalidaActionPerformed(evt);
            }
        });
        jPanel3.add(BtnSalida);
        BtnSalida.setBounds(30, 400, 110, 50);

        matrizTiBtn.setText("Dos Matrices triangulares inferior");
        matrizTiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizTiBtnActionPerformed(evt);
            }
        });
        jPanel3.add(matrizTiBtn);
        matrizTiBtn.setBounds(50, 120, 310, 40);

        matrizDispersaBtn.setText("Matriz dispersa");
        matrizDispersaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizDispersaBtnActionPerformed(evt);
            }
        });
        jPanel3.add(matrizDispersaBtn);
        matrizDispersaBtn.setBounds(420, 120, 310, 40);

        burbujaBtn.setText("Metodo de la burbuja");
        burbujaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burbujaBtnActionPerformed(evt);
            }
        });
        jPanel3.add(burbujaBtn);
        burbujaBtn.setBounds(50, 190, 310, 40);

        jButton1.setText("Busqueda lineal");
        jPanel3.add(jButton1);
        jButton1.setBounds(420, 250, 310, 40);

        jButton2.setText("Busqueda no lineal");
        jPanel3.add(jButton2);
        jButton2.setBounds(50, 320, 310, 40);

        jButton3.setText("Metodo de insersión");
        jPanel3.add(jButton3);
        jButton3.setBounds(420, 320, 310, 40);

        jButton4.setText("Pila");
        jPanel3.add(jButton4);
        jButton4.setBounds(420, 190, 310, 40);

        jButton5.setText("Cola");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(50, 250, 310, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalidaActionPerformed

    private void matrizTiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizTiBtnActionPerformed
 matrizTriangularInf newframe = new matrizTriangularInf();
        newframe.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_matrizTiBtnActionPerformed

    private void matrizDispersaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizDispersaBtnActionPerformed
        // TODO add your handling code here:
        matrizDispersa newframe = new matrizDispersa();
        newframe.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_matrizDispersaBtnActionPerformed

    private void burbujaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burbujaBtnActionPerformed
        // TODO add your handling code here:
        burbuja newframe = new burbuja();
        newframe.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_burbujaBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static String fecha(){
        Date fecha= new Date();
        SimpleDateFormat formatofecha= new SimpleDateFormat("dd / MMM / YYYY");
      
        return formatofecha.format(fecha);
        
    }
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalida;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Hora;
    private javax.swing.JButton burbujaBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton matrizDispersaBtn;
    private javax.swing.JButton matrizTiBtn;
    // End of variables declaration//GEN-END:variables
}
